import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Poppins} from 'next/font/google'
import SubscriptionModal from "@/components/SubscriptionModal";

export const metadata: Metadata = {
  title: "The Fifth",
  description: "Generated by create next app",
};

const PoppinsFont = Poppins({
  subsets:["latin"],
  weight: '300',

})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={PoppinsFont.className}>
      <body
      >
        <SubscriptionModal />
        <Header/>

        {children}
        <Footer />
      </body>
    </html>
  );
}
